### ISSUE TITLE
Test Server aufsetzen

### ISSUE THREAD

**Issue by swoadmin** [stiftungswo/izivi#1]
Originally reported by: **swo-admin NA (Bitbucket: [swo-admin](https://bitbucket.org/swo-admin), GitHub: Unknown)**

----------------------------------------

Ein Testserver für die Entwicklung aufsetzten, aktuell können wir es lokal mit npm laufen lassen (NodeJS) oder den Backend Teil mit XAMPP (Apache und MySQL). Physisch bekommen wir keinen Server, werden uns also noch was überlegen.

----------------------------------------
- Bitbucket: https://bitbucket.org/stiftungswo/izivi/issue/1

**Comment by tourn** [comment]
Der Travis CI Build sollte dies abdecken.
