### ISSUE TITLE
Laravel/Lumen Mail-Funktionalität anstatt von php mail() benutzen

### ISSUE THREAD

**Issue by cookiecavekeeper** [stiftungswo/izivi#105]
Reporter: Zivi

--------

An einigen Orten verwenden wir direkt php's mail() Funktion. Oft sowohl lokal, wie auch live.

Das mach es schwierig die mails lokal zu testen / mocken.

Darum sollten wir die Laravel / Lumen mails benutzen.

**Comment by andyundso** [comment]
Konkret:
* https://github.com/stiftungswo/izivi/blob/master/api/app/Console/Commands/SendFeedbackRemainderMails.php
* https://github.com/stiftungswo/izivi/blob/master/api/app/Http/Controllers/Auth/AuthController.php#L136
* https://github.com/stiftungswo/izivi/blob/master/api/app/Http/Controllers/Auth/ForgotPasswordController.php#L51
* https://github.com/stiftungswo/izivi/blob/master/api/app/Http/Controllers/FeedbackController.php#L236
