### ISSUE TITLE
Feedback Erinnerungsemails werden nicht verschickt

### ISSUE THREAD

**Issue by jonixis** [stiftungswo/izivi#120]
Seit ca. Mitte April 2018 sind in der DB alle flags *feedback_mail_sent* auf *0*, und zwar auch bei Missions die beendet und nicht gelöscht sind (39 Missions bis 03.08.18). 
Wahrscheinlich wurde der tägliche Job für den Versand des Reminders nicht mehr ausgeführt.

**Comment by andyundso** [comment]
Mails rückwirkend noch versenden.

**Comment by jonixis** [comment]
Cronjob nach deployment auf prod auf minütlich stellen
