### ISSUE TITLE
Nur noch eine Telefonnummer angeben

### ISSUE THREAD

**Issue by andyundso** [stiftungswo/izivi#139]
Reporter: Andi Wolf

---

Pro Zivi ist mindestens eine Telefonnummer nötig (egal ob Mobile, Privat oder Geschäftlich).

**Comment by andyundso** [comment]
Manu und Marc möchten, dass dies anders gelöst wird: Es gibt neu nur noch ein Telefonnummern-Feld. Bei den bestehenden Zivis wird dies mit Priorität Mobil > Privat > Geschäftlich abgefüllt bei der Migration.

**Comment by TheFehr** [comment]
Wird nun wieder korrekt ausgefüllt
