### ISSUE TITLE
Bootstrap-Klassen durch Bootstrap-Component-Library ersetzen

### ISSUE THREAD

**Issue by andyundso** [stiftungswo/izivi#142]
Das iZivi-Frontend ist im Moment manuell mit Klassen aufgesetzt. Wie im neuen Dime soll auch im iZivi eine Component-Library eingesetzt werden. Dies soll aber diese von Bootstrap sein, anstatt MaterialUI, damit wir das Layout +/- wieder gleich aufbauen können.

**Comment by TheFehr** [comment]
Reactstrap ist eingebunden, gewisse Edge-Cases werden nicht von der Library abgedeckt
