### ISSUE TITLE
Randomly failing test

### ISSUE THREAD

**Issue by lukasbischof** [stiftungswo/izivi#156]
Reporter: Lukas (Zivi)

---

Momentan failed ein Test im Backend von Zeit zur Zeit: https://semaphoreci.com/stiftungswo/izivi/branches/ts/builds/28

**Comment by skius** [comment]
BIC von fzaninotto/faker wurde zu locker für unsere Validation generiert. Fixed in 2e0a58926737202b698cc38ab3f8001aeec7ebfb
