### ISSUE TITLE
Zeiterfassung aus Dime im Izivi Spesenrapport übertragen

### ISSUE THREAD

**Issue by swoadmin** [stiftungswo/izivi#46]
Originally reported by: **swo-admin NA (Bitbucket: [swo-admin](https://bitbucket.org/swo-admin), GitHub: Unknown)**

----------------------------------------

Wir können die genauen Tage und Stunden eines Zivis aus Dime heraus ziehen um diese im Izivi Spesenrapport zu übernehmen. Dabei gibt es Krankheitstage, Ferien und Urlaubstage, sowie das jeweilige Projekt worauf der Zivi gearbetiet hat.

----------------------------------------
- Bitbucket: https://bitbucket.org/stiftungswo/izivi/issue/46

**Comment by andyundso** [comment]
Besprechung mit Andi: Etwa bis Ende Jahr umsetzen, hat jedoch nicht höchste Priorität.

**Comment by TheFehr** [comment]
Siehe [better-izivi#225](https://github.com/stiftungswo/better-izivi/issues/225)
