### ISSUE TITLE
E-Mail zum Feedback Zeitpunkt

### ISSUE THREAD

**Issue by swoadmin** [stiftungswo/izivi#62]
Originally reported by: **Michael Schär (Bitbucket: [angralon](https://bitbucket.org/angralon), GitHub: Unknown)**

----------------------------------------

Die E-Mail zum Ausfüllen des User-Feedbacks wird 24h zu früh an den jeweiligen Zivi verschickt.

----------------------------------------
- Bitbucket: https://bitbucket.org/stiftungswo/izivi/issue/62

**Comment by jgschwend** [comment]
Momentan werden die Email am letzten Tag des Einsatzes verschickt (00:00 Uhr).
Könnte leicht behoben werden. Notwendig?
