### ISSUE TITLE
Planungsansicht Menuposition

### ISSUE THREAD

**Issue by swoadmin** [stiftungswo/izivi#63]
Originally reported by: **Michael Schär (Bitbucket: [angralon](https://bitbucket.org/angralon), GitHub: Unknown)**

----------------------------------------

Wenn bei der Planung viele Einträge angezeigt werden, muss sehr viel gescrollt werden, um den Table-Header wieder anzuzeigen. Eine Möglichkeit wäre, die Tabelle als scrollbarer unterbereich einzubauen, so dass die Überschriften immer sichtbar sind.

Mobile ist zweitranging für die Planungsansicht.

----------------------------------------
- Bitbucket: https://bitbucket.org/stiftungswo/izivi/issue/63

**Comment by tourn** [comment]
Haben heute ausprobiert, den Tabellenheader einerseits mit CSS `position: fixed` und andererseits mit jQuery anzunageln. Problematisch ist in beiden fällen, dass dies nicht gut mit der Verwendung der `colspan` und `rowspan` im Header zusammenpasst und das ganze Layout auseinanderfällt.

Alternativ könnte man noch ausprobieren, nur den tbody zu scrollen wie [hier](http://jsfiddle.net/7UZA4/1385/), was aber nicht so hübsch aussieht.

**Comment by tourn** [comment]
Funktioniert, Feedback der User war gut.
