### ISSUE TITLE
Fehlermeldung bei der Planungsansicht

### ISSUE THREAD

**Issue by swoadmin** [stiftungswo/izivi#65]
Originally reported by: **Michael Schär (Bitbucket: [angralon](https://bitbucket.org/angralon), GitHub: Unknown)**

----------------------------------------

Beim Öffnen der Planungsansicht gibt es manchmal eine Fehlermeldung. Diese ist jedoch schwierig nachzustellen. Möglicherweise tritt der Fehler auf, wenn während dem Laden einer anderen Ansicht die Planungsansicht geöffnet wird.

Gemeldet von Manuel.

----------------------------------------
- Bitbucket: https://bitbucket.org/stiftungswo/izivi/issue/65

**Comment by tourn** [comment]
Können wir neu eröffnen, wenn das Problem wieder auftritt.
