### ISSUE TITLE
Erstellen von Meldeblätter pro Monat

### ISSUE THREAD

**Issue by swoadmin** [stiftungswo/izivi#68]
Originally reported by: **Michael Schär (Bitbucket: [angralon](https://bitbucket.org/angralon), GitHub: Unknown)**

----------------------------------------

Wenn ein Einsatz verlängert wird, sollte es die Möglichkeit geben, alle fehlenden Meldeblätter zu generieren (eines pro Monat).

Zurzeit wird über die Funktion "Meldeblatt hinzufügen" ein Meldeblatt über die ganze Einsatzdauer erstellt. Wenn der Einsatz beispielsweise um 6 Monate verlängert wird, muss die Funktion 6 mal verwendet und das  Datum jeweils angepasst werden.

----------------------------------------
- Bitbucket: https://bitbucket.org/stiftungswo/izivi/issue/68

**Comment by tourn** [comment]
Wurde mit fc7bf24 implementiert. Feature funktioniert soweit und läuft auf Produktion.
