### ISSUE TITLE
Pflichtenhefter IDs werden inkonsistent gehandhabt

### ISSUE THREAD

**Issue by tourn** [stiftungswo/izivi#73]
Reporter: Marc

Wenn unter dem Reiter "Pflichtenheft" die Checkbox von Pflichtenheft 37390 deaktiviert und *Speicher* geklickt wird, crasht das backend.

Schuldig scheint diese Zeile: https://github.com/stiftungswo/izivi/blob/b296fcceebfea4621e4165bc68901d5b1c0c96cf/api/routes/api.php#L241

**Comment by tourn** [comment]
Was eigentlich das Problem ist ist folgendes:

Pflichtenhefter mit derselben Zivildienststellen ID können mehrmals eingetragen werden, um z.B. verschiedene Gültigkeitsräume zu modellieren. z.B. werden Versionen des Pflichtenheft 123 im Backend als 123.1, 123.2 als Primary Key gespeichert, im Frontend aber als 123, 123 angezeigt. Das JSON, das von der API zurückkommt macht hier den Unterschied zwischen `id` (123) und `fullId` (123.3) - das Frontend ignoriert die *fullId* jedoch komplett und schickt requests an die Route `specification/{id}`, wodurch diese Einträge dann nicht gefunden werden.

Auch lässt die Maske zum erfassen eines neuen Pflichtenhefts nur die Angabe der `id` zu.

Im optimalfall lässt sich dies auf ein einzelnes Feld zusammenfalten (Wert von `fullId` in `id` verpacken), wobei dann das Suffix im UI an Orten wo es nicht benötigt wird wegformatiert werden kann (Wobei dies evtl für die Eingabe verwirrend ist)

**Comment by tourn** [comment]
Der Laravel Router tut sich wegen des punktes schwer, "123.2" als Route Parameter anzunehmen. Man könnte stattdessen "_" als Trennzeichen verwenden. Dies funktioniert aber nicht ohne weiteres, da das Datenbankfeld der Pflichtenhefter vom typ `double` ist. Dies ist ohnehin problematisch, da dies bei Vergleichen zu Problemen führen kann. Alternativ könnten jeweils bei API Calls `.` durch `_` ersetzt werden, wobei sich dies an diversen Stellen durch den Code zieht und unsauber wirkt.

Unabhängig des Trennzeichens würde es sich anbieten, im selben Zug gleich den Primärschlüssel der Pflichtenhefter auf einen String umzustellen. Dies müsste für saubere Nachvollziehbarkeit in den Lumen Migrations passieren.

**Comment by swoadmin** [comment]
https://sentry.io/swo/izivi/issues/434971459/

**Comment by andyundso** [comment]
TO-DO
- [ ] Migration erstellen, welche das ID-Feld von String zu TinyText ändert und die Punkte in den Nummern mit Underscores ersetzt (und auch wieder umgekehrt).
- [ ] Validation ins Model hinzufügen, welche prüft, dass lediglich Bustaben, Zahlen und Underscores erlaubt sind als ID für das Pflichtenheft.
- [ ] Überprüfen, dass die IDs im Front-End nun in voller Länge angezeigt werden.
- [ ] Ggf. API Logik mit PHPUnit testen.
- [ ] Ggf. testen, dass es nicht möglich ist, ein Pflichtenheft nochmals mit derselben ID zu erstellen.
