### ISSUE TITLE
Freie Tage für Letzten Einsatz unter 26 Tagen

### ISSUE THREAD

**Issue by tourn** [stiftungswo/izivi#78]
Der Letzte Zivildiensteinsatz darf die Minimaldauer von 26 Tagen unterschreiten. Hierbei reduziert sich jedoch die Anzahl an Freien Tagen (Wochenende, Feiertage) die an die Einsatzdauer angerechnet werden.

```
Dauer | Freie Tage
1-6   | 0
7-10  | 1
11-13 | 2
14-17 | 3
18-20 | 4
21-24 | 5
25    | 6
```

Momentan werden fälschlicherweise zu viele Frei-Tage angerechnet. Beispiel:

Plane einen "Letzten Einsatz* von 16.7 mit Einsatzdauer von 15 Tagen. Als Enddatum wird hier der 30.7 Angegeben (15 Tage später), da aber nur 3 der 4 Wochenendtage angerechnet werden sollte der Einsatz am 31.7 enden.

**Comment by cookiecavekeeper** [comment]
Es muss noch genau geklärt werden wie Ferien, Betriebsferien, Wochenenden und freie Tage zusammenspielen.

* Was zählt alles als "Freier Tag"? Wochenenden? Betriebsferien?
* Wie viele Freie Tage darf ein Einsatz mit mehr als 26 Tagen haben? Wie funktioniert der Übergang?

Um ein besseres Bild der Sache zu bekommen müssen wir das noch mit Marc abklären.

**Comment by cookiecavekeeper** [comment]
Abklären:

Aktuell werden nur Start-/Enddatum abgespeichert. Eine Möglichkeit wäre es zusätzlich die Anzahl Tage abzuspeichern. Allerdings kann dann neu das Enddatum nicht mehr bearbeitet werden, es wird beim bearbeiten der Tage berechnet.

- Wie wird das im Zusammenhang mit Meldeblättern gehandhabt? Sie berechnen aktuell auch die Anzahl Tage.
  - was wenn ein verkürzter Einsatz übers Monatsende geht. Wieviele Freie Tage hat er dann noch (woher kriegen wir die Info?)?

Evtl. lassen wir einfach alles wie es ist und bemerken das es Änderungen geben kann....

**Comment by cookiecavekeeper** [comment]
Abgeklärt:

Die Meldeblätter müssen neu zusammen mit den anderen Meldeblättern des Einsatzes auf verkürzte Einsätze Rücksicht nehmen. Also müssen sie wissen wie viele Freie Tage insgesamt verfügbar sind und wie viele bereits benutzt worden sind.

**Comment by andyundso** [comment]
Done:
* Funktion implementiert, welche anhand von zwei Daten die Einsatzdauern rechnet, unter Berücksichtigung von Feiertagen, evt. langer oder letzter Einsatz sowie Betriebsferien.

Abklären:
* Es gibt bestimmte Edge-Cases, bei welchem der kurze Einsatz zu lang werden kann, z.B. muss man noch 6 Tage absolvieren und beginnt seinen Einsatz am Montag. Der Einsatz würde dann theoretisch am Samstag enden, was dann aber nicht geht, weil das Wochenende nicht dazu gezählt wird aufgrund der kurzen Einsatzdauer. Wenn der Einsatz bis Sonntag gemacht wird, wird ein Wochenendtag gezählt, womit man auf seine sechs Einsatztage kommt. 

Paul hat dies aber momentan so implementiert, dass wenn der Einsatz auf ein Wochenende endet, automatisch Tage dazugezählt werden, damit der Einsatz an einem Werktag, also folglich am Montag endet. Damit wäre der Einsatz aber sieben Tage lang (5 Tage erste Woche, 1 anrechenbarer Wochenendtag + der Montag). Darf der Einsatz in einem solchen Fall an einem Sonntag enden, anstatt an einem Werktag?

To-Do:
* Pauls ursprüngliche Funktion oder meine Funktion aufgrund oberer Abklärung anpassen, Tests korrigieren, damit diese laufen (Seeds für die Feiertage im Moment noch unvollständig!).
* Neues Datenbankfeld hinzufügen für verwendete Freitage beim ReportSheet, falls es sich um den letzten Einsatz handelt und dieser unter 26 Tage ist, damit wir dies monatsübergreifend tracken können.
* Neue SQL-Abfrage beim Rechnen des ReportSheets überprüfen, damit nicht zu viele Freitag angerechnet werden.
* Test hinzufügen (Summe der Report-Sheets-Tage sollte der Berechnung der Einsatzdauern des gesamten Einsatzes entsprechen).

**Comment by andyundso** [comment]
Auskunft von Marc: Die Wochenend-Tage müssen als Urlaubstage verbucht werden, wenn das Kontingent der arbeitsfreien Tage erschöpft ist.

**Comment by tourn** [comment]
> Auskunft von Marc: Die Wochenend-Tage müssen als Urlaubstage verbucht werden, wenn das Kontingent der arbeitsfreien Tage erschöpft ist.

> Funktion implementiert, welche anhand von zwei Daten die Einsatzdauern rechnet, unter Berücksichtigung von Feiertagen, evt. langer oder letzter Einsatz sowie Betriebsferien.

Die Funktion muss also eigentlich mit dem *Startdatum* und *Anzahl Einsatztage* arbeiten. Denn aus Anfangs/Enddatum lässt sich nicht immer eindeutig die Einsatzdauer bestimmen:

* 6 Freie Tage: Montag - Montag, wobei Sa/So als Urlaub gebucht werden
* 7 Freie Tage: Montag - Montag, wobei Sa als Arbeitstag und So als urlaub gebucht werden.
