### ISSUE TITLE
Warnung, wenn keine aktuellen Feiertage vorhanden sind

### ISSUE THREAD

**Issue by tourn** [stiftungswo/izivi#91]
Reporter: Andi

----

Reminder Email an swo@stiftungswo.ch, ein Monat + 3 Wochen bevor Letzte in iZivi eingetragene Ferientag vorbei ist.

Cronjob auf Cyon einrichten

**Comment by cookiecavekeeper** [comment]
Implementiert in 360fe88

Sobald dieser commit auf prod deployed ist kann der cronjob eingerichtet werden

Das command kann mit `php artisan command:check-holiday` ausgeführt werden (wohl anders auf cyon)

**Comment by tourn** [comment]
Cronjob ist eingerichtet.
